libc_a_SOURCES += \
	%D%/close.c \
	%D%/dup.c \
	%D%/execve.c \
	%D%/fcntl.c \
	%D%/fork.c \
	%D%/fstat.c \
	%D%/getentropy.c \
	%D%/getpid.c \
	%D%/gettimeofday.c \
	%D%/isatty.c \
	%D%/kill.c \
	%D%/link.c \
	%D%/lseek.c \
	%D%/mkdir.c \
	%D%/open.c \
	%D%/read.c \
	%D%/rename.c \
	%D%/sbrk.c \
	%D%/stat.c \
	%D%/syscalls.c \
	%D%/times.c \
	%D%/unlink.c \
	%D%/wait.c \
	%D%/write.c
